import type { NextPage } from "next";
import Head from "next/head";
import AwardWinning from "../components/awardWinning/AwardWinning";
import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";
import Passion from "../components/passion/Passion";
import Project from "../components/projects/Project";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title className="">Designo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <AwardWinning />
      <Project />
      <Passion />
      <Footer />
    </div>
  );
};

export default Home;
