import type { NextPage } from "next";
import Head from "next/head";
import AwardWinning from "../components/awardWinning/AwardWinning";
import Passion from "../components/passion/Passion";
import Project from "../components/projects/Project";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Designo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <AwardWinning />
      <Project />
      <Passion />
    </div>
  );
};

export default Home;
